events {
    worker_connections 1024;
}

http {
    # DNS Docker interne — résolution dynamique à chaque requête
    resolver 127.0.0.11 valid=30s ipv6=off;

    server {
        listen 80;
        server_name _;

        # Frontend
        location / {
            set $upstream_frontend http://frontend:3000;
            proxy_pass $upstream_frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API
        location /api/ {
            set $upstream_backend http://backend:3001;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass $upstream_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Grafana
        location /grafana/ {
            set $upstream_grafana http://grafana:3000;
            proxy_pass $upstream_grafana;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Adminer
        location /adminer/ {
            set $upstream_adminer http://adminer:8080;
            proxy_pass $upstream_adminer;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
